title: Great awesome blog
author: Kensation
email: kensation@example.com
description: > # this means to ignore newlines until "baseurl:"
 Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 Maecenas id faucibus elit. Cras elit arcu, lacinia eget
 congue quis, venenatis lobortis est. Pellentesque a est
 massa. Aliquam est elit, porttitor id tortor id, imperdiet
 consectetur turpis. Praesent ultricies quam augue, vitae
 suscipit mi molestie in. Sed ut erat vitae nulla aliquet
 tristique. Quisque iaculis bibendum semper. Duis mollis
 turpis sapien. Nulla nunc tortor, tristique vitae leo vel,
 egestas tempor elit. Aliquam sed posuere urna. Quisque
 consectetur risus ut massa ornare, id mattis nisl pulvinar.
 Duis vitae erat sem. Integer iaculis, ex non condimentum tempus,
 dui dui elementum purus, sed lobortis arcu dolor quis nibh.
# social links
twitter_username: kensation # DO NOT include the @ character, or else the build will fail!
github_username:  kensation # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
